<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <include filename="$(find bandit_urdf)/defs/head.gazebo.xacro" />
  <include filename="$(find bandit_urdf)/defs/head.transmission.xacro" />

  <property name="M_PI" value="3.1415926535897931" />
  <property name="neck_height" value="0.076"/>
  <property name="neck_radius" value="0.03175"/>

	<property name="head_length" value="0.145"/>
	<property name="head_width" value="0.145"/>
	<property name="torso_height" value="0.299"/>
	<property name="neck_height" value="0.040"/>
	<property name="head_height" value="0.155"/>

  <xacro:macro name="bandit_head_pan" params="name parent *origin">
    <joint name="${name}_joint" type="revolute">
			<origin xyz="0 0 ${.0825 + (neck_height/2)-0.01}"/>
			<!--<origin xyz="0 0 ${(body_height/2) + (neck_height/2)-0.01}"/>-->
      <axis xyz="0 0 1"/>
      <limit lower="-1.57079633" upper="1.57079633" effort="2.645" velocity="6" />
      <safety_controller k_velocity="1.5" soft_lower_limit="${-1.57079633+0.15}" 
	soft_upper_limit="${1.57079633-0.15}" k_position="100" />
      <calibration reference_position="0.0" />
      <dynamics damping="1.0" />
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>


    <link name="${name}_link">
      <inertial>
        <mass value="0"/>
        <origin xyz="-0.05 0 -0.101" rpy="183.928 0 -90"/>
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925" />
      </inertial>
      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*-90}"/>
        <geometry name="${name}_visual_geom">
					<mesh filename="package://bandit_urdf/meshes/bandit_mesh/neck_smallest.stl"/>
        </geometry>
					<material name="Neck"/>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*90}"/>
        <geometry name="${name}_visual_geom">
		<box size="0 0 0"/>
        </geometry>
      </collision>
    </link>


    <!-- extensions -->
    <xacro:bandit_head_pan_gazebo name="${name}" />
    <xacro:bandit_head_pan_transmission name="${name}" />

	</xacro:macro>

	<xacro:macro name="bandit_head_tilt" params="name parent *origin">
    <joint name="${name}_joint" type="revolute">
      <axis xyz="0 -1 ${(head_height/4)}" />
      <limit lower="-0.261799388" upper="0.261799388" effort="2.645" velocity="6" />
      <safety_controller k_velocity="1.5" soft_lower_limit="${-1.57079633+0.15}" soft_upper_limit="${1.57079633-0.15}" k_position="100" />
      <calibration reference_position="0.0" />
      <dynamics damping="1.0" />
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="0" />
        <origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*90}"/>
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925"/>
      </inertial>
      <visual name="${name}_visual">
        <origin xyz="-.02 0 .01" rpy="${RCon*90} 0 ${RCon*90}"/>
        <!--<origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*90}"/>-->

	<!-- -->
        <geometry name="${name}_visual_geom">
		<mesh filename="package://bandit_urdf/meshes/bandit_mesh/head_smallest.stl"/>
        </geometry>
					<material name="Head"/>
      </visual>

      <collision name="${name}_collision">
         <origin xyz="0.008 0 0.055" rpy="0 0 0 " />
        <geometry name="${name}_visual_geom">
		<box size="0.147 0.156 0.16"/>
        </geometry>
      </collision>
    </link>



    <!-- extensions -->
    <xacro:bandit_head_tilt_gazebo name="${name}" />
    <xacro:bandit_head_tilt_transmission name="${name}" />


	</xacro:macro>

	<xacro:macro name="bandit_eye" params="name parent *origin">
	  <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="0" />
        <origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*90}"/>
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925"/>
      </inertial>
      <visual name="${name}_visual">
        <origin xyz="0.035 0 0" rpy="${RCon*90} 0 ${RCon*-90}"/>

        <geometry name="${name}_visual_geom">
					<mesh filename="package://bandit_urdf/meshes/bandit_mesh/camera_board_smallest.stl"/>
        </geometry>
					<!--  <material name="Silver"/>  -->
					<material name="texture">
					<texture filename="package://bandit_urdf/meshes/bandit_mesh/gradients/reflect1.jpg"/>
					</material>
      </visual>

      <collision name="${name}_collision">
         <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry name="${name}_visual_geom">
					<box size="0 0 0"/>
        </geometry>
      </collision>
    </link>


</xacro:macro>
	<xacro:macro name="bandit_eyebrow" params="name parent side reflect *origin">
    <joint name="${name}_joint" type="revolute">
      <axis xyz="0 ${reflect} 0" />
      <limit lower="-0.261799388" upper="0.261799388" effort="2.645" velocity="6" />
      <safety_controller k_velocity="1.5" soft_lower_limit="${-1.57079633+0.15}" soft_upper_limit="${1.57079633-0.15}" k_position="100" />
      <calibration reference_position="0.0" />
      <dynamics damping="1.0" />
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="0" />
        <origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*90}"/>
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925"/>
      </inertial>
      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="0 0 ${RCon*-90}"/>
        <geometry name="${name}_visual_geom">
					<mesh filename="package://bandit_urdf/meshes/bandit_mesh/eyebrow_${side}_smallest.stl"/>
        </geometry>
					<material name="Eyebrows"/>
      </visual>

      <collision name="${name}_collision">
         <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry name="${name}_visual_geom">
					<box size="0 0 0"/>
        </geometry>
      </collision>
    </link>
	</xacro:macro>

	<xacro:macro name="bandit_lips" params="name parent *origin">
	  <joint name="${name}_joint" type="revolute">
		<axis xyz="0 -1 0" />
		<limit lower="-0.261799388" upper="0.261799388" effort="2.645" velocity="6" />
      		<safety_controller k_velocity="1.5" soft_lower_limit="${-1.57079633+0.15}" soft_upper_limit="${1.57079633-0.15}" k_position="100" />
     		<calibration reference_position="0.0" />
      		<dynamics damping="1.0" />
 
      		<insert_block name="origin" />
      		<parent link="${parent}"/>
      		<child link="${name}_link"/>
   	  </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="0" />
        <origin xyz="0 0 0" rpy="0 0 ${RCon*90}"/>
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925"/>
      </inertial>
      <visual name="${name}_visual">
        <origin xyz="0 0 .002" rpy="0 0 ${RCon*-90}"/>
        <!--<origin xyz="0 0 -0.035" rpy="${RCon*0} 0 ${RCon*-90}"/>-->
        <!--<origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*90}"/>-->

	<!-- -->
        <geometry name="${name}_visual_geom">
					<mesh filename="package://bandit_urdf/meshes/bandit_mesh/top_lip_smallest.STL"/>
        </geometry>
					<material name="Lips"/>
      </visual>

      <collision name="${name}_collision">
         <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry name="${name}_visual_geom">
					<box size="0 0 0"/>
        </geometry>
      </collision>
    </link>
	  <joint name="${name}2_joint" type="revolute">
		<axis xyz="0 -1 0"/>
		<limit lower="-0.261799388" upper="0.261799388" effort="2.645" velocity="6" />
      		<safety_controller k_velocity="1.5" soft_lower_limit="${-1.57079633+0.15}" soft_upper_limit="${1.57079633-0.15}" k_position="100" />
     		<calibration reference_position="0.0" />
      		<dynamics damping="1.0" />
 
      		<insert_block name="origin" />
      		<parent link="${parent}"/>
      		<child link="${name}2_link"/>
   	  </joint>
    <link name="${name}2_link">
      <inertial>
        <mass value="0" />
        <origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*90}"/>
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925"/>
      </inertial>
      <visual name="${name}2_visual">
        <origin xyz="0 0 -0.002" rpy="0 0 ${RCon*-90}"/>
        <!--<origin xyz="0 0 -0.035" rpy="${RCon*0} 0 ${RCon*-90}"/>-->
        <!--<origin xyz="0 0 0" rpy="${RCon*90} 0 ${RCon*90}"/>-->

	<!-- -->
        <geometry name="${name}2_visual_geom">
					<mesh filename="package://bandit_urdf/meshes/bandit_mesh/bottom_lip_smallest.stl"/>
        </geometry>
					<material name="Lips"/>
      </visual>

      <collision name="${name}2_collision">
         <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry name="${name}2_visual_geom">
					<box size="0 0 0"/>
        </geometry>
      </collision>
    </link>
</xacro:macro>

	<xacro:macro name="bandit_head" params="name parent *origin">
		<xacro:bandit_head_pan name="${name}_pan" parent="${parent}">
			<insert_block name="origin"/>
		</xacro:bandit_head_pan>
		<xacro:bandit_head_tilt name="${name}_tilt" parent="${name}_pan_link">
			<origin xyz="0.00 0 0.02" rpy="0 0 0"/>

		</xacro:bandit_head_tilt>
		<xacro:bandit_eye name="${name}_right_camera" parent="${name}_tilt_link">
			<origin xyz="0.05 -0.0320 .060" rpy="0 ${M_PI/2} 0"/>
		</xacro:bandit_eye>
		<xacro:bandit_eye name="${name}_left_camera" parent="${name}_tilt_link">
			<origin xyz="0.05 0.0320 .060" rpy="0 ${M_PI/2} 0"/>
		</xacro:bandit_eye>
		<xacro:bandit_eyebrow name="${name}_left_brow" parent="${name}_tilt_link" side="left" reflect="1">
			<origin xyz="0.06 0.0470 .085" rpy="${-M_PI/2} ${-M_PI/2} 0"/>
		</xacro:bandit_eyebrow>
		<xacro:bandit_eyebrow name="${name}_right_brow" parent="${name}_tilt_link" side="right" reflect="-1">
			<origin xyz="0.06 -0.0470 .085" rpy="${-M_PI/2} ${-M_PI/2} 0"/>
		</xacro:bandit_eyebrow>

		<xacro:bandit_lips name="${name}_lips" parent="${name}_tilt_link">
			<origin xyz="0.070 0.0 -0.0075" rpy="0 0 0"/>
		</xacro:bandit_lips>

		<!--<xacro:bandit_head_gazebo name="${name}"/>-->
	</xacro:macro>

<xacro:macro name="pupil" params="suffix reflect">
	<joint name="pupil_${suffix}_joint" type="fixed">
		<origin xyz="0.0012 ${reflect*0.001} -0.032" rpy="0 0 0"/>
		<parent link="bandit_head_${suffix}_camera_link"/>
		<child link="pupil_${suffix}_link"/>
	</joint>

	<link name="pupil_${suffix}_link">
		<inertial>
			<mass value="0"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1" ixy="0" ixz="0"
				 iyy="1" iyz="0" izz="1"/>
  	 	</inertial>
		<visual name="pupil_visual">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry name="pupil_left_geom">
				<mesh filename="package://bandit_urdf/meshes/bandit_mesh/middle_eye_smallest.stl"/>
			</geometry>
		<material name="Pupil">
			<color rgba="0 0 0 1"/>
		</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0 0 0"/>
			</geometry>
		</collision>
	</link>
</xacro:macro>

<xacro:pupil suffix="left" reflect="-4.8"/>
<xacro:pupil suffix="right" reflect="-4.6"/>

</robot>
